### PR TITLE
Added ollama and openai Fastapi api services

### PR DESCRIPTION
**Pull request by ParisNeo**
# Add FastAPI Services for LightRAG Integration

## Overview
Added two FastAPI services that provide REST API endpoints for utilizing LightRAG in distributed applications:
1. Ollama-based FastAPI service
2. OpenAI-based FastAPI service

These services enable easy integration of LightRAG capabilities into existing applications through HTTP endpoints.

### Common Features
- Multiple search modes (naive, local, global, hybrid)
- Streaming and non-streaming query responses
- Document management (insert, upload, batch processing)
- Health monitoring endpoints
- Automatic API documentation (Swagger/ReDoc)
- Configurable working directories
- Asynchronous operation support

### Ollama Service Specific
- Configurable Ollama host
- Support for various Ollama models
- Default integration with mistral-nemo and bge-m3
- Adjustable async operation limits
- Custom embedding dimensions

### OpenAI Service Specific
- OpenAI API integration
- Support for latest GPT models
- text-embedding-3-large integration
- Automatic embedding dimension detection
- nest-asyncio implementation for better async handling

### Ollama Service
```bash
--host: Server host (default: 0.0.0.0)
--port: Server port (default: 9621)
--model: LLM model name (default: mistral-nemo:latest)
--embedding-model: Embedding model (default: bge-m3:latest)
--ollama-host: Ollama host URL
--working-dir: RAG storage location
--max-async: Maximum concurrent operations
--max-tokens: Token limit
--embedding-dim: Embedding dimensions
--max-embed-tokens: Embedding token limit
```

### OpenAI Service
```bash
--host: Server host (default: 0.0.0.0)
--port: Server port (default: 9621)
--model: OpenAI model (default: gpt-4)
--embedding-model: Embedding model (default: text-embedding-3-large)
--working-dir: RAG storage location
--max-tokens: Token limit
--max-embed-tokens: Embedding token limit
```

## API Endpoints

Both services provide:
- `/query`: Document querying
- `/query/stream`: Streaming responses
- `/documents/text`: Text insertion
- `/documents/file`: File upload
- `/documents/batch`: Batch file processing
- `/documents/scan`: Directory scanning
- `/health`: System status

### Query Example
```bash
curl -X POST "http://localhost:9621/query" \
    -H "Content-Type: application/json" \
    -d '{"query": "Your question", "mode": "hybrid"}'
```

### Document Upload
```bash
curl -X POST "http://localhost:9621/documents/file" \
    -F "file=@document.txt"
```

## Testing
- Tested with various document sizes
- Verified streaming functionality
- Confirmed batch processing capabilities
- Validated error handling
- Checked memory management

## Documentation
- Included detailed README for both services
- Added API documentation
- Provided configuration guides
- Included usage examples

## Future Improvements
- Add support for more model providers
- Implement caching mechanisms
- Add authentication/authorization
- Enhance error handling
- Add monitoring metrics

## Dependencies
- FastAPI
- Uvicorn
- LightRAG
- Pydantic
- OpenAI/Ollama clients
- Python 3.8+

This PR significantly enhances LightRAG's usability in distributed environments and makes it easier to integrate with existing applications.

### CODE REVIEW

**Comment by LarFii** [comment]
Thanks for your contribution! But there are some linting errors. Please make sure to run pre-commit run --all-files before submitting to ensure all linting checks pass.

**Comment by ParisNeo** [comment]
Hi there. Thanks alot for answering me.
I just run the linting fix.

Best regards

**Comment by ParisNeo** [comment]
By the way, why don't you put this directly as a github action to automatically apply linting to the project?

**Comment by LarFii** [comment]
Thank you again for your incredible contribution! It seems that automation can't fix all the linting errors, so some manual adjustments are still needed.

**Comment by ParisNeo** [comment]
You are welcome.
I even added lightrag to my Tool lollms as a service. So the user can setup a server with lightrag then he can use lollms as front end to chat with his AI using his vectorized data.

For now there is ollama and openai, But I'll add more services for other backends.

Thanks for accepting my contribution.
Best regards

**Pull request merged**
