### PR TITLE
fixing knowledge_graph keyword bug

### PR DESCRIPTION
**Pull request by Yazington**
#133 #132

### CODE REVIEW

**Comment by Dormiveglia-elf** [comment]
Please refer to PR #123 
I think that you didn't modify anything bro.

**Comment by LarFii** [comment]
The typos have been fixed in the latest code. : )

**Comment by tackhwa** [comment]
@LarFii i think there is still few typo `knwoledge_graph_inst`  in `operate.py`, can you please fix it?

**Comment by LarFii** [comment]
You're right; that was an oversight on my part. I'll fix it right now.

**Comment by Yazington** [comment]
was using  ruff formatter I think might be reason why builds are failing

**Pull request merged**
